# Are players allowed to give other players CrateKeys? (This applies to ops only)
PlayerGive: false

# Where is the CrateKey block located?
X: 0
Y: 0
Z: 0
World: world

# How many items will the player recieve when they use a CrateKey?
Number: 4

# List of items to give a player when they use a CrateKey. This will be randomised
Items:
  - "264"
  - "265"
  - "364"
  - "388"
  
# List of commands to run when a player gets a CrateKey
# Use {PLAYER} for the player, and {NAME} for the player's name
Commands:
    - say {NAME} got a CrateKey!
    - tell {PLAYER} Thank you for buying a CrateKey! You can use your CrateKey where the CrateKey block is placed.
